#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfc1f;
constexpr uint24_t FX_DATA_BYTES = 249982;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Death = 0x018580;
  constexpr uint24_t SFX_Victory = 0x018624;
  constexpr uint24_t SFX_XPGain = 0x0186D8;
  constexpr uint24_t SFX_Three_Inc = 0x0186EC;
  constexpr uint24_t SFX_Three_Dec = 0x018708;
  constexpr uint24_t SFX_PlayerBlip = 0x018724;
  constexpr uint24_t SFX_EnemyBlip = 0x018734;
  constexpr uint24_t SFX_Explosion = 0x018744;
  constexpr uint24_t SFX_DoubleBeep = 0x018788;
  constexpr uint24_t SFX_DoubleBeepDown = 0x018798;
  constexpr uint24_t SFX_Bet1 = 0x0187A8;
  constexpr uint24_t SFX_Bet2 = 0x0187B0;
  constexpr uint24_t SFX_Bet3 = 0x0187B8;
  constexpr uint24_t SFX_Bet4 = 0x0187C0;
  constexpr uint24_t SFX_Bet5 = 0x0187C8;
  constexpr uint24_t SFX_Bet6 = 0x0187D0;
  constexpr uint24_t SFX_Click = 0x0187D8;
  constexpr uint24_t SFX_SmallBlind = 0x0187E0;
  constexpr uint24_t SFX_BigBlind = 0x0187E8;
}

namespace Constants
{
  constexpr uint24_t Starting_Bids = 0x0187F8;
  constexpr uint24_t Score_Panel_XTextPos = 0x0187FE;
  constexpr uint24_t Score_Panel_XPanelPos = 0x018804;
  constexpr uint24_t Score_Panel_Idx = 0x01880A;
}

namespace Images
{
  constexpr uint24_t Flip = 0x018810;
  constexpr uint24_t Cards_Bottom = 0x019A12;
  constexpr uint24_t Cards_Bottom_Grey = 0x01DBE4;
  constexpr uint24_t Hand_Full = 0x021DB6;
  constexpr uint24_t Hand_Full_Grey = 0x021E51;
  constexpr uint24_t Title = 0x021EEC;
  constexpr uint24_t PPOT = 0x022674;
  constexpr uint24_t Scoundrel = 0x025676;
  constexpr uint24_t Fire = 0x026278;
  constexpr uint24_t HUD = 0x03227A;
  constexpr uint24_t Background = 0x0324BC;
  constexpr uint24_t Equip = 0x032B4E;
  constexpr uint24_t BurnCard = 0x0333E4;
  constexpr uint24_t RestoreHealth = 0x033B5A;
  constexpr uint24_t ChooseFight = 0x034534;
  constexpr uint24_t Numbers_5x3_2D_MB = 0x035F3A;
  constexpr uint24_t Numbers_5x3_2D_WB = 0x036770;
  constexpr uint24_t Puff_00 = 0x036FA6;
  constexpr uint24_t Puff_01 = 0x0387A8;
  constexpr uint24_t Run = 0x039FAA;
  constexpr uint24_t Sword = 0x03A078;
  constexpr uint24_t YouLose = 0x03BE7A;
  constexpr uint24_t YouWin = 0x03CA7C;
}

